modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/drewhannay/lantern-colors/issues" #optional
[[mods]] #mandatory
modId="lanterncolors" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Lantern Colors" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="" #optional - TODO: Look into this when publishing
displayURL="https://github.com/drewhannay/lantern-colors" #optional
logoFile="logo.png" #optional
# credits="" #optional
authors="drewhannay" #optional
description='''
This mod adds lantern variants for every dye color.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.lanterncolors]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.lanterncolors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
